meta :crontab do
  accepts_list_for :user
  accepts_list_for :lines
  template {
    helper(:crontab) { "/var/spool/cron/crontabs" / user.first }
    met? { !File.writable?(crontab) ?  sudo("grep 'Generated by babushka' #{crontab}") : babushka_config?(crontab) }
    meet { append_to_file lines.join("\n") + "\n\n", crontab, :sudo => !File.writable?(crontab) }
  }
end
