dep 'delayed job running' do
  requires 'daemons.gem', 'delayed job monit configured'
  # can we check they're actually running?
end

dep 'delayed job monit configured' do
  helper(:monitrc) { "/etc/monit/conf.d/dj.#{var(:app_name)}.monitrc" }
  met? { sudo "grep 'Generated by babushka' #{monitrc}" }
  meet { render_erb "monit/dj.monitrc.erb", :to => monitrc, :sudo => true }
  after { sudo "monit reload" }
end

dep 'daemons.gem' do
  provides []
end
