dep 'sphinx.src' do
  source "http://www.sphinxsearch.com/downloads/sphinx-0.9.8.tar.gz"
  provides 'search', 'searchd', 'indexer'
end

dep 'sphinx running' do
  requires 'sphinx.src', 'sphinx configured', 'sphinx monit configured'
  helper(:sphinx_pid) { "/var/run " / var(:app_name) / "sphinx.pid" }
  met? { sphinx_pid.exist? && shell("ps `cat #{sphinx_pid}`") }
  meet { sudo "monit restart sphinx_#{var(:app_name)}" }
end

dep 'sphinx configured' do
  helper(:sphinx_config) { var(:rails_root) / 'config' / 'sphinx.yml' }
  met? { sphinx_config.exists? }
  meet { "shell cp #{var(:rails_root) / "config" / "sphinx.#{var(:rails_env)}.yml"} #{sphinx_config}" }
end

dep 'sphinx monit configured' do
  requires 'monit running', 'writable monit pid directory'
  helper(:monitrc) { "/etc/monit/conf.d/sphinx.#{var(:app_name)}.monitrc" }
  met? { sudo "grep 'Generated by babushka' #{monitrc}" }
  meet { render_erb "monit/sphinx.monitrc.erb", :to => monitrc, :sudo => true }
  after { sudo "monit reload" }
end
